package m0;

import B1.b;

public abstract class y {
    public static final e a;
    public static final e b;
    public static final e c;
    public static final e d;
    public static final e e;
    public static final e f;
    public static final e g;
    public static final e h;
    public static final e i;
    public static final e j;
    public static final e k;
    public static final e l;
    public static final e m;
    public static final e n;
    public static final e o;
    public static final e p;
    public static final e q;
    public static final e r;
    public static final e s;

    static {
        b b0 = e.a();
        b0.a = 3;
        b0.b = "Google Play In-app Billing API version is less than 3";
        y.a = b0.a();
        b b1 = e.a();
        b1.a = 3;
        b1.b = "Google Play In-app Billing API version is less than 9";
        y.b = b1.a();
        b b2 = e.a();
        b2.a = 3;
        b2.b = "Billing service unavailable on device.";
        y.c = b2.a();
        b b3 = e.a();
        b3.a = 2;
        b3.b = "Billing service unavailable on device.";
        y.d = b3.a();
        b b4 = e.a();
        b4.a = 5;
        b4.b = "Client is already in the process of connecting to billing service.";
        y.e = b4.a();
        b b5 = e.a();
        b5.a = 5;
        b5.b = "The list of SKUs can\'t be empty.";
        b5.a();
        b b6 = e.a();
        b6.a = 5;
        b6.b = "SKU type can\'t be empty.";
        b6.a();
        b b7 = e.a();
        b7.a = 5;
        b7.b = "Product type can\'t be empty.";
        y.f = b7.a();
        b b8 = e.a();
        b8.a = -2;
        b8.b = "Client does not support extra params.";
        y.g = b8.a();
        b b9 = e.a();
        b9.a = 5;
        b9.b = "Invalid purchase token.";
        y.h = b9.a();
        b b10 = e.a();
        b10.a = 6;
        b10.b = "An internal error occurred.";
        y.i = b10.a();
        b b11 = e.a();
        b11.a = 5;
        b11.b = "SKU can\'t be null.";
        b11.a();
        b b12 = e.a();
        b12.a = 0;
        y.j = b12.a();
        b b13 = e.a();
        b13.a = -1;
        b13.b = "Service connection is disconnected.";
        y.k = b13.a();
        b b14 = e.a();
        b14.a = 2;
        b14.b = "Timeout communicating with service.";
        y.l = b14.a();
        b b15 = e.a();
        b15.a = -2;
        b15.b = "Client does not support subscriptions.";
        y.m = b15.a();
        b b16 = e.a();
        b16.a = -2;
        b16.b = "Client does not support subscriptions update.";
        b16.a();
        b b17 = e.a();
        b17.a = -2;
        b17.b = "Client does not support get purchase history.";
        b17.a();
        b b18 = e.a();
        b18.a = -2;
        b18.b = "Client does not support price change confirmation.";
        b18.a();
        b b19 = e.a();
        b19.a = -2;
        b19.b = "Play Store version installed does not support cross selling products.";
        b19.a();
        b b20 = e.a();
        b20.a = -2;
        b20.b = "Client does not support multi-item purchases.";
        y.n = b20.a();
        b b21 = e.a();
        b21.a = -2;
        b21.b = "Client does not support offer_id_token.";
        y.o = b21.a();
        b b22 = e.a();
        b22.a = -2;
        b22.b = "Client does not support ProductDetails.";
        y.p = b22.a();
        b b23 = e.a();
        b23.a = -2;
        b23.b = "Client does not support in-app messages.";
        b23.a();
        b b24 = e.a();
        b24.a = -2;
        b24.b = "Client does not support user choice billing.";
        b24.a();
        b b25 = e.a();
        b25.a = -2;
        b25.b = "Play Store version installed does not support external offer.";
        b25.a();
        b b26 = e.a();
        b26.a = -2;
        b26.b = "Play Store version installed does not support multi-item purchases with season pass in one cart.";
        b26.a();
        b b27 = e.a();
        b27.a = 5;
        b27.b = "Unknown feature";
        b27.a();
        b b28 = e.a();
        b28.a = -2;
        b28.b = "Play Store version installed does not support get billing config.";
        b28.a();
        b b29 = e.a();
        b29.a = -2;
        b29.b = "Query product details with serialized docid is not supported.";
        b29.a();
        b b30 = e.a();
        b30.a = 4;
        b30.b = "Item is unavailable for purchase.";
        y.q = b30.a();
        b b31 = e.a();
        b31.a = -2;
        b31.b = "Query product details with developer specified account is not supported.";
        b31.a();
        b b32 = e.a();
        b32.a = -2;
        b32.b = "Play Store version installed does not support alternative billing only.";
        b32.a();
        b b33 = e.a();
        b33.a = 5;
        b33.b = "To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.";
        y.r = b33.a();
        b b34 = e.a();
        b34.a = 6;
        b34.b = "An error occurred while retrieving billing override.";
        y.s = b34.a();
    }

    public static e a(int v, String s) {
        b b0 = e.a();
        b0.a = v;
        b0.b = s;
        return b0.a();
    }
}

