package com.google.android.gms.measurement.internal;

import android.content.Context;
import com.google.android.gms.common.util.VisibleForTesting;
import com.google.android.gms.internal.measurement.zzhe;
import com.google.android.gms.internal.measurement.zzhp;
import i1.k;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Map;

@VisibleForTesting
public final class zzeh {
    public static final List a;
    public static final zzeg zzA;
    public static final zzeg zzB;
    public static final zzeg zzC;
    public static final zzeg zzD;
    public static final zzeg zzE;
    public static final zzeg zzF;
    public static final zzeg zzG;
    public static final zzeg zzH;
    public static final zzeg zzI;
    public static final zzeg zzJ;
    public static final zzeg zzK;
    public static final zzeg zzL;
    public static final zzeg zzM;
    public static final zzeg zzN;
    public static final zzeg zzO;
    public static final zzeg zzP;
    public static final zzeg zzQ;
    public static final zzeg zzR;
    public static final zzeg zzS;
    public static final zzeg zzT;
    public static final zzeg zzU;
    public static final zzeg zzV;
    public static final zzeg zzW;
    public static final zzeg zzX;
    public static final zzeg zzY;
    public static final zzeg zzZ;
    public static final zzeg zza;
    public static final zzeg zzaA;
    public static final zzeg zzaB;
    public static final zzeg zzaC;
    public static final zzeg zzaD;
    public static final zzeg zzaE;
    public static final zzeg zzaF;
    public static final zzeg zzaG;
    public static final zzeg zzaH;
    public static final zzeg zzaa;
    public static final zzeg zzab;
    public static final zzeg zzac;
    public static final zzeg zzad;
    public static final zzeg zzae;
    public static final zzeg zzaf;
    public static final zzeg zzag;
    public static final zzeg zzah;
    public static final zzeg zzai;
    public static final zzeg zzaj;
    public static final zzeg zzak;
    public static final zzeg zzal;
    public static final zzeg zzam;
    public static final zzeg zzan;
    public static final zzeg zzao;
    public static final zzeg zzap;
    public static final zzeg zzaq;
    public static final zzeg zzar;
    public static final zzeg zzas;
    public static final zzeg zzat;
    public static final zzeg zzau;
    public static final zzeg zzav;
    public static final zzeg zzaw;
    public static final zzeg zzax;
    public static final zzeg zzay;
    public static final zzeg zzaz;
    public static final zzeg zzb;
    public static final zzeg zzc;
    public static final zzeg zzd;
    public static final zzeg zze;
    public static final zzeg zzf;
    public static final zzeg zzg;
    public static final zzeg zzh;
    public static final zzeg zzi;
    public static final zzeg zzj;
    public static final zzeg zzk;
    public static final zzeg zzl;
    public static final zzeg zzm;
    public static final zzeg zzn;
    public static final zzeg zzo;
    public static final zzeg zzp;
    public static final zzeg zzq;
    public static final zzeg zzr;
    public static final zzeg zzs;
    public static final zzeg zzt;
    public static final zzeg zzu;
    public static final zzeg zzv;
    public static final zzeg zzw;
    public static final zzeg zzx;
    public static final zzeg zzy;
    public static final zzeg zzz;

    static {
        zzeh.a = Collections.synchronizedList(new ArrayList());
        Collections.synchronizedSet(new HashSet());
        zzeh.zza = zzeh.a("measurement.ad_id_cache_time", 10000L, 10000L, zzbj.zza);
        zzeh.zzb = zzeh.a("measurement.monitoring.sample_period_millis", 86400000L, 86400000L, zzbb.zza);
        zzeh.zzc = zzeh.a("measurement.config.cache_time", 86400000L, 3600000L, zzbn.zza);
        zzeh.zzd = zzeh.a("measurement.config.url_scheme", "https", "https", zzbz.zza);
        zzeh.zze = zzeh.a("measurement.config.url_authority", "app-measurement.com", "app-measurement.com", zzcl.zza);
        zzeh.zzf = zzeh.a("measurement.upload.max_bundles", 100, 100, zzcx.zza);
        zzeh.zzg = zzeh.a("measurement.upload.max_batch_size", 0x10000, 0x10000, zzdj.zza);
        zzeh.zzh = zzeh.a("measurement.upload.max_bundle_size", 0x10000, 0x10000, zzdv.zza);
        zzeh.zzi = zzeh.a("measurement.upload.max_events_per_bundle", 1000, 1000, zzdz.zza);
        zzeh.zzj = zzeh.a("measurement.upload.max_events_per_day", 100000, 100000, zzea.zza);
        zzeh.zzk = zzeh.a("measurement.upload.max_error_events_per_day", 1000, 1000, zzbu.zza);
        zzeh.zzl = zzeh.a("measurement.upload.max_public_events_per_day", 50000, 50000, zzcf.zza);
        zzeh.zzm = zzeh.a("measurement.upload.max_conversions_per_day", 10000, 10000, zzcq.zza);
        zzeh.zzn = zzeh.a("measurement.upload.max_realtime_events_per_day", 10, 10, zzdb.zza);
        zzeh.zzo = zzeh.a("measurement.store.max_stored_events_per_app", 100000, 100000, zzdm.zza);
        zzeh.zzp = zzeh.a("measurement.upload.url", "https://app-measurement.com/a", "https://app-measurement.com/a", zzdx.zza);
        zzeh.zzq = zzeh.a("measurement.upload.backoff_period", 43200000L, 43200000L, zzeb.zza);
        zzeh.zzr = zzeh.a("measurement.upload.window_interval", 3600000L, 3600000L, zzec.zza);
        zzeh.zzs = zzeh.a("measurement.upload.interval", 3600000L, 3600000L, zzaz.zza);
        zzeh.zzt = zzeh.a("measurement.upload.realtime_upload_interval", 10000L, 10000L, zzba.zza);
        zzeh.zzu = zzeh.a("measurement.upload.debug_upload_interval", 1000L, 1000L, zzbc.zza);
        zzeh.zzv = zzeh.a("measurement.upload.minimum_delay", 500L, 500L, zzbd.zza);
        zzeh.zzw = zzeh.a("measurement.alarm_manager.minimum_interval", 60000L, 60000L, zzbe.zza);
        zzeh.zzx = zzeh.a("measurement.upload.stale_data_deletion_interval", 86400000L, 86400000L, zzbf.zza);
        zzeh.zzy = zzeh.a("measurement.upload.refresh_blacklisted_config_interval", 604800000L, 604800000L, zzbg.zza);
        zzeh.zzz = zzeh.a("measurement.upload.initial_upload_delay_time", 15000L, 15000L, zzbh.zza);
        zzeh.zzA = zzeh.a("measurement.upload.retry_time", 1800000L, 1800000L, zzbi.zza);
        zzeh.zzB = zzeh.a("measurement.upload.retry_count", 6, 6, zzbk.zza);
        zzeh.zzC = zzeh.a("measurement.upload.max_queue_time", 2419200000L, 2419200000L, zzbl.zza);
        zzeh.zzD = zzeh.a("measurement.lifetimevalue.max_currency_tracked", 4, 4, zzbm.zza);
        zzeh.zzE = zzeh.a("measurement.audience.filter_result_max_count", 200, 200, zzbo.zza);
        zzeh.zzF = zzeh.a("measurement.upload.max_public_user_properties", 25, 25, null);
        zzeh.zzG = zzeh.a("measurement.upload.max_event_name_cardinality", 500, 500, null);
        zzeh.zzH = zzeh.a("measurement.upload.max_public_event_params", 25, 25, null);
        zzeh.zzI = zzeh.a("measurement.service_client.idle_disconnect_millis", 5000L, 5000L, zzbp.zza);
        zzeh.zzJ = zzeh.a("measurement.test.boolean_flag", Boolean.FALSE, Boolean.FALSE, zzbq.zza);
        zzeh.zzK = zzeh.a("measurement.test.string_flag", "---", "---", zzbr.zza);
        zzeh.zzL = zzeh.a("measurement.test.long_flag", -1L, -1L, zzbs.zza);
        zzeh.zzM = zzeh.a("measurement.test.int_flag", -2, -2, zzbt.zza);
        zzeh.zzN = zzeh.a("measurement.test.double_flag", -3.0, -3.0, zzbv.zza);
        zzeh.zzO = zzeh.a("measurement.experiment.max_ids", 50, 50, zzbw.zza);
        zzeh.zzP = zzeh.a("measurement.max_bundles_per_iteration", 100, 100, zzbx.zza);
        zzeh.zzQ = zzeh.a("measurement.sdk.attribution.cache.ttl", 604800000L, 604800000L, zzby.zza);
        zzeh.zzR = zzeh.a("measurement.redaction.app_instance_id.ttl", 7200000L, 7200000L, zzca.zza);
        zzeh.zzS = zzeh.a("measurement.collection.log_event_and_bundle_v2", Boolean.TRUE, Boolean.TRUE, zzcb.zza);
        zzeh.zzT = zzeh.a("measurement.quality.checksum", Boolean.FALSE, Boolean.FALSE, null);
        zzeh.zzU = zzeh.a("measurement.audience.use_bundle_end_timestamp_for_non_sequence_property_filters", Boolean.FALSE, Boolean.FALSE, zzcc.zza);
        zzeh.zzV = zzeh.a("measurement.audience.refresh_event_count_filters_timestamp", Boolean.FALSE, Boolean.FALSE, zzcd.zza);
        zzeh.zzW = zzeh.a("measurement.audience.use_bundle_timestamp_for_event_count_filters", Boolean.FALSE, Boolean.FALSE, zzce.zza);
        zzeh.zzX = zzeh.a("measurement.sdk.collection.retrieve_deeplink_from_bow_2", Boolean.TRUE, Boolean.TRUE, zzcg.zza);
        zzeh.zzY = zzeh.a("measurement.sdk.collection.last_deep_link_referrer_campaign2", Boolean.FALSE, Boolean.FALSE, zzch.zza);
        zzeh.zzZ = zzeh.a("measurement.lifecycle.app_in_background_parameter", Boolean.FALSE, Boolean.FALSE, zzci.zza);
        zzeh.zzaa = zzeh.a("measurement.integration.disable_firebase_instance_id", Boolean.FALSE, Boolean.FALSE, zzcj.zza);
        zzeh.zzab = zzeh.a("measurement.collection.service.update_with_analytics_fix", Boolean.FALSE, Boolean.FALSE, zzck.zza);
        zzeh.zzac = zzeh.a("measurement.client.firebase_feature_rollout.v1.enable", Boolean.TRUE, Boolean.TRUE, zzcm.zza);
        zzeh.zzad = zzeh.a("measurement.client.sessions.check_on_reset_and_enable2", Boolean.TRUE, Boolean.TRUE, zzcn.zza);
        zzeh.zzae = zzeh.a("measurement.collection.synthetic_data_mitigation", Boolean.FALSE, Boolean.FALSE, zzco.zza);
        zzeh.zzaf = zzeh.a("measurement.service.storage_consent_support_version", 203600, 203600, zzcp.zza);
        zzeh.zzag = zzeh.a("measurement.client.click_identifier_control.dev", Boolean.FALSE, Boolean.FALSE, zzcr.zza);
        zzeh.zzah = zzeh.a("measurement.service.click_identifier_control", Boolean.FALSE, Boolean.FALSE, zzcs.zza);
        zzeh.zzai = zzeh.a("measurement.module.pixie.fix_array", Boolean.TRUE, Boolean.TRUE, zzct.zza);
        zzeh.zzaj = zzeh.a("measurement.adid_zero.only_request_adid_if_enabled", Boolean.TRUE, Boolean.TRUE, zzcu.zza);
        zzeh.zzak = zzeh.a("measurement.service.refactor.package_side_screen", Boolean.TRUE, Boolean.TRUE, zzcv.zza);
        zzeh.zzal = zzeh.a("measurement.enhanced_campaign.service", Boolean.TRUE, Boolean.TRUE, zzcw.zza);
        zzeh.zzam = zzeh.a("measurement.enhanced_campaign.client", Boolean.TRUE, Boolean.TRUE, zzcy.zza);
        zzeh.zzan = zzeh.a("measurement.enhanced_campaign.srsltid.client", Boolean.TRUE, Boolean.TRUE, zzcz.zza);
        zzeh.zzao = zzeh.a("measurement.enhanced_campaign.srsltid.service", Boolean.TRUE, Boolean.TRUE, zzda.zza);
        zzeh.zzap = zzeh.a("measurement.service.store_null_safelist", Boolean.TRUE, Boolean.TRUE, zzdc.zza);
        zzeh.zzaq = zzeh.a("measurement.service.store_safelist", Boolean.TRUE, Boolean.TRUE, zzdd.zza);
        zzeh.zzar = zzeh.a("measurement.redaction.no_aiid_in_config_request", Boolean.TRUE, Boolean.TRUE, zzde.zza);
        zzeh.zzas = zzeh.a("measurement.redaction.config_redacted_fields", Boolean.TRUE, Boolean.TRUE, zzdf.zza);
        zzeh.zzat = zzeh.a("measurement.redaction.upload_redacted_fields", Boolean.TRUE, Boolean.TRUE, zzdg.zza);
        zzeh.zzau = zzeh.a("measurement.redaction.upload_subdomain_override", Boolean.TRUE, Boolean.TRUE, zzdh.zza);
        zzeh.zzav = zzeh.a("measurement.redaction.device_info", Boolean.TRUE, Boolean.TRUE, zzdi.zza);
        zzeh.zzaw = zzeh.a("measurement.redaction.user_id", Boolean.TRUE, Boolean.TRUE, zzdk.zza);
        zzeh.zzax = zzeh.a("measurement.redaction.google_signals", Boolean.TRUE, Boolean.TRUE, zzdl.zza);
        zzeh.zzay = zzeh.a("measurement.collection.enable_session_stitching_token.service", Boolean.FALSE, Boolean.FALSE, zzdn.zza);
        zzeh.zzaz = zzeh.a("measurement.collection.enable_session_stitching_token.client.dev", Boolean.FALSE, Boolean.FALSE, zzdo.zza);
        zzeh.zzaA = zzeh.a("measurement.redaction.app_instance_id", Boolean.TRUE, Boolean.TRUE, zzdp.zza);
        zzeh.zzaB = zzeh.a("measurement.redaction.populate_ephemeral_app_instance_id", Boolean.TRUE, Boolean.TRUE, zzdq.zza);
        zzeh.zzaC = zzeh.a("measurement.redaction.enhanced_uid", Boolean.TRUE, Boolean.TRUE, zzdr.zza);
        zzeh.zzaD = zzeh.a("measurement.redaction.e_tag", Boolean.TRUE, Boolean.TRUE, zzds.zza);
        zzeh.zzaE = zzeh.a("measurement.redaction.client_ephemeral_aiid_generation", Boolean.TRUE, Boolean.TRUE, zzdt.zza);
        zzeh.zzaF = zzeh.a("measurement.redaction.retain_major_os_version", Boolean.TRUE, Boolean.TRUE, zzdu.zza);
        zzeh.zzaG = zzeh.a("measurement.redaction.scion_payload_generator", Boolean.FALSE, Boolean.FALSE, zzdw.zza);
        zzeh.zzaH = zzeh.a("measurement.audience.dynamic_filters.oob_fix", Boolean.TRUE, Boolean.TRUE, zzdy.zza);
    }

    public static zzeg a(String s, Object object0, Object object1, k k0) {
        zzeg zzeg0 = new zzeg(s, object0, object1, k0);
        zzeh.a.add(zzeg0);
        return zzeg0;
    }

    public static Map zzc(Context context0) {
        zzhe zzhe0 = zzhe.zza(context0.getContentResolver(), zzhp.zza("com.google.android.gms.measurement"), zzay.zza);
        return zzhe0 == null ? Collections.emptyMap() : zzhe0.zzc();
    }
}

